version: "3.9"

services:
  dB:
    container_name: dB
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --init-file /docker-entrypoint-initdb.d/propylon.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: propylon@test123
    volumes:
      - ./datasource:/docker-entrypoint-initdb.d
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE

  backend_service:
    container_name: backend_service
    ports:
      - 8001:8001
    volumes:
      - ./:/app
    command: python manage.py runserver 0:8001

    environment:
      - DB_PASSWORD=propylon@test123
    depends_on:
      - dB

    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - RUNNING_ENV=local

    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000/ping"]
    #   timeout: 10s
    #   retries: 3
    #   start_period: 30s

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 7700:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=0.0.0.0
    depends_on:
      - dB
