# Generated by Django 4.1.9 on 2023-12-15 22:41

from django.conf import settings
from django.db import migrations, models
import propylon_document_manager.file_versions.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("file_versions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="files",
            old_name="file_name",
            new_name="file_url",
        ),
        migrations.AddField(
            model_name="fileversion",
            name="uploaded_file",
            field=models.FileField(
                default="", upload_to=propylon_document_manager.file_versions.models.get_upload_path
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="files",
            unique_together={("file_url", "user")},
        ),
    ]
