# Generated by Django 4.1.9 on 2023-12-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0002_rename_file_name_files_file_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="files",
            name="file_name",
            field=models.CharField(default="", max_length=512),
            preserve_default=False,
        ),
    ]
